// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "smartRecursion.mode": string;
      "summaryBanner.enabled": boolean;
      "summaryBanner.minItems": number;
      "sourceColumn.enabled": boolean;
      "sourceColumn.separator": string;
      "readingStatus.enabled": boolean;
      "readingStatus.tagPrefix": string;
      "exportBundle.enabled": boolean;
      "exportBundle.includeFulltext": boolean;
      "exportBundle.outputDir": string;
      "libraryAudit.enabled": boolean;
      "libraryAudit.outputDir": string;
      "metadataClean.enabled": boolean;
      "metadataClean.fixHtml": boolean;
      "metadataClean.normalizeLanguage": boolean;
      "structuredFields.enabled": boolean;
      "structuredFields.prefix": string;
      "structuredFields.outputDir": string;
      "dev.openPrefsOnStart": boolean;
      "dev.initialCategory": string;
    };
  }
}
